### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by T0lk13n** [chris-y/avalanche#1]
First of all, thanks for Avalanche. A simple but effective interface. Just what I need.

Perhaps Im used to MUI but dont know how to set the size of the window. By default it is very small and dont want to resize it everytime I use it. Perhaps there is a Reaction settings to save it?

**Comment by chris-y** [comment]
OS4 ReAction has a built-in snapshot/unsnapshot/restore feature.  This doesn't appear to have made it to the OS3.2 version (probably because it relies on new Intuition features and classes that haven't been written/back-ported to OS3.2 yet)

Therefore this will need a bit of manual effort to implement, but is doable.
